/**
 * EzDocSeal
 * The easiest API to sign PDF documents, creating a blue bar. You provide a name, e-mail address, location and reason and the result is a signed PDF document. If you want more features and/or control we suggest to use our PDF stamper API.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The JsonSignResponse model module.
* @module SphereonSDKEzDocseal/model/JsonSignResponse
* @version 0.1.0
*/
export default class JsonSignResponse {
    /**
    * Constructs a new <code>JsonSignResponse</code>.
    * @alias module:SphereonSDKEzDocseal/model/JsonSignResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>JsonSignResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:SphereonSDKEzDocseal/model/JsonSignResponse} obj Optional instance to populate.
    * @return {module:SphereonSDKEzDocseal/model/JsonSignResponse} The populated <code>JsonSignResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JsonSignResponse();
                        
            
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} content
    */
    'content' = undefined;




}
