/**
 * EzDocSeal
 * The easiest API to sign PDF documents, creating a blue bar. You provide a name, e-mail address, location and reason and the result is a signed PDF document. If you want more features and/or control we suggest to use our PDF stamper API.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SignData from './SignData';

/**
* The JsonSignRequest model module.
* @module SphereonSDKEzDocseal/model/JsonSignRequest
* @version 0.1.0
*/
export default class JsonSignRequest {
    /**
    * Constructs a new <code>JsonSignRequest</code>.
    * @alias module:SphereonSDKEzDocseal/model/JsonSignRequest
    * @class
    * @param signData {module:SphereonSDKEzDocseal/model/SignData} 
    * @param content {String} 
    */

    constructor(signData, content) {
        
        
        this['signData'] = signData;
        this['content'] = content;
        
    }

    /**
    * Constructs a <code>JsonSignRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:SphereonSDKEzDocseal/model/JsonSignRequest} obj Optional instance to populate.
    * @return {module:SphereonSDKEzDocseal/model/JsonSignRequest} The populated <code>JsonSignRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JsonSignRequest();
                        
            
            if (data.hasOwnProperty('signData')) {
                obj['signData'] = SignData.constructFromObject(data['signData']);
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:SphereonSDKEzDocseal/model/SignData} signData
    */
    'signData' = undefined;
    /**
    * @member {String} content
    */
    'content' = undefined;




}
