/**
 * EzDocSeal
 * The easiest API to sign PDF documents, creating a blue bar. You provide a name, e-mail address, location and reason and the result is a signed PDF document. If you want more features and/or control we suggest to use our PDF stamper API.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The SignData model module.
* @module SphereonSDKEzDocseal/model/SignData
* @version 0.1.0
*/
export default class SignData {
    /**
    * Constructs a new <code>SignData</code>.
    * @alias module:SphereonSDKEzDocseal/model/SignData
    * @class
    * @param emailAddress {String} 
    * @param name {String} 
    */

    constructor(emailAddress, name) {
        
        
        this['emailAddress'] = emailAddress;
        this['name'] = name;
        
    }

    /**
    * Constructs a <code>SignData</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:SphereonSDKEzDocseal/model/SignData} obj Optional instance to populate.
    * @return {module:SphereonSDKEzDocseal/model/SignData} The populated <code>SignData</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SignData();
                        
            
            if (data.hasOwnProperty('emailAddress')) {
                obj['emailAddress'] = ApiClient.convertToType(data['emailAddress'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} emailAddress
    */
    'emailAddress' = undefined;
    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {String} location
    */
    'location' = undefined;
    /**
    * @member {String} reason
    */
    'reason' = undefined;




}
