/**
 * EzDocSeal
 * The easiest API to sign PDF documents, creating a blue bar. You provide a name, e-mail address, location and reason and the result is a signed PDF document. If you want more features and/or control we suggest to use our PDF stamper API.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import Error from '../model/Error';
import JsonSignRequest from '../model/JsonSignRequest';
import JsonSignResponse from '../model/JsonSignResponse';

/**
* Default service.
* @module SphereonSDKEzDocseal/api/DefaultApi
* @version 0.1.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:SphereonSDKEzDocseal/api/DefaultApi
    * @class
    * @param {module:SphereonSDKEzDocseal/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:SphereonSDKEzDocseal/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the sign operation.
     * @callback module:SphereonSDKEzDocseal/api/DefaultApi~signCallback
     * @param {String} error Error message, if any.
     * @param {module:SphereonSDKEzDocseal/model/JsonSignResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:SphereonSDKEzDocseal/api/DefaultApi~signCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:SphereonSDKEzDocseal/model/JsonSignResponse}
     */
    sign(body, callback) {
      let postBody = body;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['api_key'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = JsonSignResponse;

      return this.apiClient.callApi(
        '/sign', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
